### ISSUE TITLE
Error "failed to load plugin" after update

### ISSUE THREAD

**Issue by aadhil-aslam** [muhammadv-i/obsidian-frontmatter-alias-display#6] opened 2023-05-06 16:08 UTC
![image](https://user-images.githubusercontent.com/84399420/236634959-cdf91b05-4b99-437e-8d8c-13540daa6c6f.jpeg)

**Comment by chaosmonster** [comment] 2023-05-08 16:13
It seems that `titleEl` from here https://github.com/muhammadv-i/obsidian-frontmatter-alias-display/blob/0bc5eacbda423975d7edb70c79eff190f177b2c7/main.ts#L10 is not existing

**Comment by aadhil-aslam** [comment] 2023-05-08 16:17
what do you mean by not existing

What is the solution?

**Comment by notmuhammad** [comment] 2023-05-10 14:33
Hi @aadhil-aslam, the bug is now fixed. Please update your plugin. Thanks for letting me know about it.

Also, thank you for the heads up and saving my time @chaosmonster :)

**Closed** 2023-05-10 14:33 UTC
Labels: bug

**Comment by aadhil-aslam** [comment] 2023-05-10 14:37
Great its solved now!
But why file name is now center aligned after the update. Is that a bug or how to change it?

**Comment by notmuhammad** [comment] 2023-05-10 15:39
I see no problem on my end:
![image](https://github.com/muhammadv-i/obsidian-frontmatter-alias-display/assets/76049040/ca408638-91ab-4cbc-9dd2-003d4a7823ef)

Maybe there's a theme or another plugin installed on your end that's affecting the styling. Let me know if you found the cause of that problem.
